"""policies_snapshot_history — optional rollback log for hot-reload swaps
(Slice-4 PR-S4-4 / ADR-0023).

Revision ID: 0013
Revises: 0012
Create Date: 2026-06-07 00:00:00.000000

See ADR-0023 (mtime-polled hot-reload for ``config/policies.yaml``) and
``docs/superpowers/plans/2026-06-07-slice-4-pr-s4-0b-migrations-infra-i18n.md``
§B for the contract this migration realises.

``policies_snapshot_history`` holds one row per loaded ``PoliciesV1``
snapshot. ``PolicyWatcher`` (PR-S4-4) appends a row on every successful
swap; the table is OPTIONAL — disabling it loses rollback history but
does not affect runtime behaviour (the live snapshot lives in process
memory via ``PoliciesSnapshotRef``).

Columns
-------

* ``snapshot_id`` — UUID PK. Generated by PR-S4-4's ``PolicyWatcher``
  at swap time. CHECK pins the canonical UUID v4 hex shape so a future
  refactor cannot accidentally widen the type and lose collision
  resistance.
* ``loaded_at`` — timestamptz of the successful load + swap.
* ``file_sha256`` — 64-char hex of the ``config/policies.yaml`` bytes
  that produced this snapshot. Doubles as the watcher's idempotency
  short-circuit (PR-S4-4 round-2 closure 4). CHECK pins the SHA-256
  hex format so a future refactor to a different hash recipe is refused
  at the DB layer.
* ``policies_json`` — full JSON serialisation of the swapped-in
  ``PoliciesV1`` instance. Stored as JSONB so operators can pivot on
  individual keys via ``alfred policies show --at-snapshot <id>``
  (future CLI; PR-S4-4 ships the audit, not the CLI).
* ``swapped_from_snapshot_id`` — UUID of the previous snapshot, NULL
  for the bootstrap snapshot. Self-reference foreign key preserving
  the snapshot lineage; ``ON DELETE RESTRICT`` so a forensic baseline
  cannot be silently removed mid-chain (PR #209 sec-3 closure — SET NULL
  would have silently broken lineage reconstructability with no audit
  trace, violating CLAUDE.md hard rule 7 "no silent failures").
* ``applied_by_operator_session_id`` — 64-char hex FK to
  ``operator_sessions.token_hash``. NULL when the swap was watcher-auto
  (no operator session involved); non-NULL when an ``alfred policies
  reload`` CLI command drove the swap. CHECK pins the hex format.
  ``ON DELETE SET NULL`` so revoking an operator session keeps the
  snapshot row alive.

  **Important — forensic attribution lives in ``audit_log``, not in
  this column.** The canonical record of WHO drove a swap is the
  ``CONFIG_RELOAD_FIELDS`` audit-log row with its ``operator_user_id``
  field. This column is just the live-session LINK used to render
  ``alfred policies show`` lineage when sessions are still active.
  Forensic replay should NEVER rely on this column being non-NULL
  (PR #209 sec-1 closure).

Indexes
-------

* PRIMARY KEY on ``snapshot_id`` named
  ``uq_policies_snapshot_history_snapshot_id`` — Postgres auto-creates
  the unique btree. UUID lookup is the canonical join key for
  forensic replay.
* ``ix_policies_snapshot_history_loaded_at`` covers the time-range
  query path (``WHERE loaded_at BETWEEN :since AND :until``).

Constraints
-----------

* ``ck_policies_snapshot_history_snapshot_id_uuid_hex`` — pins the
  canonical UUID hex shape (``8-4-4-4-12`` with dashes).
* ``ck_policies_snapshot_history_file_sha256_hex`` — pins the
  SHA-256 hex 64-char shape.
* ``ck_policies_snapshot_history_applied_by_hex`` — pins the
  ``applied_by_operator_session_id`` SHA-256 hex shape (64 chars)
  when non-NULL.
* ``ck_policies_snapshot_history_policies_json_size`` — caps the
  serialised JSONB at 256 KB (defence-in-depth against direct-INSERT
  bypass of the PR-S4-4 watcher's application-layer cap).

Downgrade
---------

DROP TABLE. Rollback history lost; live snapshot in
``PoliciesSnapshotRef`` is unaffected. Symmetric fail-soft via
``op.execute("DROP TABLE IF EXISTS ...")`` so a retried rollback after
a transient ops error completes cleanly.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0013"
down_revision: str | Sequence[str] | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

__all__ = [
    "branch_labels",
    "depends_on",
    "down_revision",
    "downgrade",
    "revision",
    "upgrade",
]


_UUID_HEX_REGEX = "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"


def upgrade() -> None:
    """Create policies_snapshot_history table + indexes + CHECK constraints."""
    op.create_table(
        "policies_snapshot_history",
        sa.Column("snapshot_id", sa.String(36), nullable=False),
        sa.Column("loaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("file_sha256", sa.String(64), nullable=False),
        sa.Column("policies_json", postgresql.JSONB(), nullable=False),
        sa.Column(
            "swapped_from_snapshot_id",
            sa.String(36),
            sa.ForeignKey(
                "policies_snapshot_history.snapshot_id",
                ondelete="RESTRICT",
            ),
            nullable=True,
        ),
        sa.Column(
            "applied_by_operator_session_id",
            sa.String(64),
            sa.ForeignKey(
                "operator_sessions.token_hash",
                ondelete="SET NULL",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name="uq_policies_snapshot_history_snapshot_id"),
        sa.CheckConstraint(
            f"snapshot_id ~ '{_UUID_HEX_REGEX}'",
            name="ck_policies_snapshot_history_snapshot_id_uuid_hex",
        ),
        sa.CheckConstraint(
            "file_sha256 ~ '^[0-9a-f]{64}$'",
            name="ck_policies_snapshot_history_file_sha256_hex",
        ),
        sa.CheckConstraint(
            "applied_by_operator_session_id IS NULL "
            "OR applied_by_operator_session_id ~ '^[0-9a-f]{64}$'",
            name="ck_policies_snapshot_history_applied_by_hex",
        ),
        # Defence-in-depth size cap (PR #209 sec-2 closure): the
        # PR-S4-4 watcher caps file bytes at 256 KB; this CHECK pins the
        # same ceiling on the materialised JSON so a direct INSERT
        # (operator psql, raw migration data-op, broken writer) cannot
        # bypass the application-layer cap and DoS the toast store.
        sa.CheckConstraint(
            "octet_length(policies_json::text) <= 262144",
            name="ck_policies_snapshot_history_policies_json_size",
        ),
    )
    op.create_index(
        "ix_policies_snapshot_history_loaded_at",
        "policies_snapshot_history",
        ["loaded_at"],
        unique=False,
    )


def downgrade() -> None:
    """Drop policies_snapshot_history; rollback history lost on revert.

    Symmetric fail-soft: both the index drop AND the table drop use
    ``IF EXISTS`` so a retried rollback after a transient ops error
    completes cleanly without leaving ``alembic_version`` half-applied.
    """
    op.drop_index(
        "ix_policies_snapshot_history_loaded_at",
        table_name="policies_snapshot_history",
        if_exists=True,
    )
    op.execute("DROP TABLE IF EXISTS policies_snapshot_history")
